# Jekyll settings
pygments: true
markdown: kramdown
permalink: /:categories/:year/:month/:title
exclude: README.md
destination: ~/Sites/belkadan/blog

# Required site details
title: -dealloc
base-url: http://counterpoint.local/~jordy/belkadan/blog

# Required for Atom feeds.
permid: tag:belkadan.com,2007:dealloc

# "Optional" site details
subtitle: The Belkadan Software Blog
author: Jordy Rose
favicon: /~jordy/belkadan/favicon
disqus: dealloc

# For services like Disqus that use a ping for validations
offline: false
