# Jekyll settings
pygments: true
markdown: kramdown
permalink: /:categories/:year/:month/:title/
exclude: README.md tapir.yml

# Required, always!
title: -dealloc

# Required. Must include the domain if using Disqus.
baseurl: http://belkadan.com/blog

# Required for Atom feeds
# This can be any URI, but tag URIs are easy
permid: tag:belkadan.com,2007:dealloc

# "Optional" site details
subtitle: The Belkadan Software Blog
author: Jordy Rose
home_title: -dealloc // The Belkadan Software Blog
min_tag_size: 2
disqus: dealloc

# Optional. Relative to baseurl. Must be on the same site!
favicon: /favicon

# Optional. Shown on pages without a category. URL is relative to baseurl.
header_title: Belkadan Software
header_url: /

# For services like Disqus that use a ping for validations
#offline: true

